# Para acessar o banco -> http://localhost:8080/h2-console e colocar a url -> jdbc:h2:mem:forum
# Sempre com o projeto rodando
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:api
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
